// <auto-generated />
using System;
using DriveToGetDataWebsitePrototype.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriveToGetDataWebsitePrototype.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240930204005_AddCircuits")]
    partial class AddCircuits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DriveToGetDataWebsitePrototype.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DriveToGetDataWebsitePrototype.Models.Circuit", b =>
                {
                    b.Property<string>("CircuitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CircuitId");

                    b.ToTable("Circuit", (string)null);

                    b.HasData(
                        new
                        {
                            CircuitId = "albert_park",
                            CircuitName = "Albert Park Grand Prix Circuit",
                            Country = "Australia",
                            Locality = "Melbourne"
                        },
                        new
                        {
                            CircuitId = "americas",
                            CircuitName = "Circuit of the Americas",
                            Country = "USA",
                            Locality = "Austin"
                        },
                        new
                        {
                            CircuitId = "bahrain",
                            CircuitName = "Bahrain International Circuit",
                            Country = "Bahrain",
                            Locality = "Sakhir"
                        },
                        new
                        {
                            CircuitId = "baku",
                            CircuitName = "Baku City Circuit",
                            Country = "Azerbaijan",
                            Locality = "Baku"
                        },
                        new
                        {
                            CircuitId = "catalunya",
                            CircuitName = "Circuit de Barcelona-Catalunya",
                            Country = "Spain",
                            Locality = "Montmelo"
                        },
                        new
                        {
                            CircuitId = "hungaroring",
                            CircuitName = "Hungaroring",
                            Country = "Hungary",
                            Locality = "Budapest"
                        },
                        new
                        {
                            CircuitId = "imola",
                            CircuitName = "Autodromo Enzo e Dino Ferrari",
                            Country = "Italy",
                            Locality = "Imola"
                        },
                        new
                        {
                            CircuitId = "interlagos",
                            CircuitName = "Autodromo Jose Carlos Pace",
                            Country = "Brazil",
                            Locality = "Sao Paulo"
                        },
                        new
                        {
                            CircuitId = "jeddah",
                            CircuitName = "Jeddah Corniche Circuit",
                            Country = "Saudi Arabia",
                            Locality = "Jeddah"
                        },
                        new
                        {
                            CircuitId = "losail",
                            CircuitName = "Losail International Circuit",
                            Country = "Qatar",
                            Locality = "Al Daayen"
                        },
                        new
                        {
                            CircuitId = "marina_bay",
                            CircuitName = "Marina Bay Street Circuit",
                            Country = "Singapore",
                            Locality = "Marina Bay"
                        },
                        new
                        {
                            CircuitId = "miami",
                            CircuitName = "Miami International Autodrome",
                            Country = "USA",
                            Locality = "Miami"
                        },
                        new
                        {
                            CircuitId = "monaco",
                            CircuitName = "Circuit de Monaco",
                            Country = "Monaco",
                            Locality = "Monte Carlo"
                        },
                        new
                        {
                            CircuitId = "monza",
                            CircuitName = "Autodromo Nazionale di Monza",
                            Country = "Italy",
                            Locality = "Monza"
                        },
                        new
                        {
                            CircuitId = "red_bull_ring",
                            CircuitName = "Red Bull Ring",
                            Country = "Austria",
                            Locality = "Spielberg"
                        },
                        new
                        {
                            CircuitId = "ricard",
                            CircuitName = "Circuit Paul Ricard",
                            Country = "France",
                            Locality = "Le Castellet"
                        },
                        new
                        {
                            CircuitId = "rodriguez",
                            CircuitName = "Autodromo Hermanos Rodriguez",
                            Country = "Mexico",
                            Locality = "Mexico City"
                        },
                        new
                        {
                            CircuitId = "shanghai",
                            CircuitName = "Shanghai International Circuit",
                            Country = "China",
                            Locality = "Shanghai"
                        },
                        new
                        {
                            CircuitId = "silverstone",
                            CircuitName = "Silverstone Circuit",
                            Country = "UK",
                            Locality = "Silverstone"
                        },
                        new
                        {
                            CircuitId = "spa",
                            CircuitName = "Circuit de Spa-Francorchamps",
                            Country = "Belgium",
                            Locality = "Spa"
                        },
                        new
                        {
                            CircuitId = "suzuka",
                            CircuitName = "Suzuka Circuit",
                            Country = "Japan",
                            Locality = "Suzuka"
                        },
                        new
                        {
                            CircuitId = "vegas",
                            CircuitName = "Las Vegas Strip Street Circuit",
                            Country = "USA",
                            Locality = "Las Vegas"
                        },
                        new
                        {
                            CircuitId = "villeneuve",
                            CircuitName = "Circuit Gilles Villeneuve",
                            Country = "Canada",
                            Locality = "Montreal"
                        },
                        new
                        {
                            CircuitId = "yas_marina",
                            CircuitName = "Yas Marina Circuit",
                            Country = "UAE",
                            Locality = "Abu Dhabi"
                        },
                        new
                        {
                            CircuitId = "zandvoort",
                            CircuitName = "Circuit Zandvoort",
                            Country = "Netherlands",
                            Locality = "Zandvoort"
                        });
                });

            modelBuilder.Entity("DriveToGetDataWebsitePrototype.Models.Constructor", b =>
                {
                    b.Property<string>("ConstructorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConstructorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConstructorId");

                    b.ToTable("Constructor", (string)null);

                    b.HasData(
                        new
                        {
                            ConstructorId = "alpine",
                            ConstructorName = "Alpine F1 Team",
                            Nationality = "French"
                        },
                        new
                        {
                            ConstructorId = "astone_martin",
                            ConstructorName = "Aston Martin",
                            Nationality = "British"
                        },
                        new
                        {
                            ConstructorId = "ferrari",
                            ConstructorName = "Ferrari",
                            Nationality = "Italian"
                        },
                        new
                        {
                            ConstructorId = "haas",
                            ConstructorName = "Haas F1 Team",
                            Nationality = "American"
                        },
                        new
                        {
                            ConstructorId = "mclaren",
                            ConstructorName = "McLaren",
                            Nationality = "British"
                        },
                        new
                        {
                            ConstructorId = "mercedes",
                            ConstructorName = "Mercedes",
                            Nationality = "German"
                        },
                        new
                        {
                            ConstructorId = "rb",
                            ConstructorName = "RB F1 Team",
                            Nationality = "Italian"
                        },
                        new
                        {
                            ConstructorId = "red_bull",
                            ConstructorName = "Red Bull",
                            Nationality = "Austrian"
                        },
                        new
                        {
                            ConstructorId = "sauber",
                            ConstructorName = "Sauber",
                            Nationality = "Swiss"
                        },
                        new
                        {
                            ConstructorId = "williams",
                            ConstructorName = "Williams",
                            Nationality = "British"
                        });
                });

            modelBuilder.Entity("DriveToGetDataWebsitePrototype.Models.Driver", b =>
                {
                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermanentNumber")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.ToTable("Driver", (string)null);

                    b.HasData(
                        new
                        {
                            DriverId = "hamilton",
                            FamilyName = "Hamilton",
                            GivenName = "Lewis",
                            Nationality = "British",
                            PermanentNumber = 44
                        },
                        new
                        {
                            DriverId = "bottas",
                            FamilyName = "Bottas",
                            GivenName = "Valtteri",
                            Nationality = "Finnish",
                            PermanentNumber = 77
                        },
                        new
                        {
                            DriverId = "verstappen",
                            FamilyName = "Verstappen",
                            GivenName = "Max",
                            Nationality = "Dutch",
                            PermanentNumber = 1
                        },
                        new
                        {
                            DriverId = "perez",
                            FamilyName = "Perez",
                            GivenName = "Sergio",
                            Nationality = "Mexican",
                            PermanentNumber = 11
                        },
                        new
                        {
                            DriverId = "norris",
                            FamilyName = "Norris",
                            GivenName = "Lando",
                            Nationality = "British",
                            PermanentNumber = 4
                        },
                        new
                        {
                            DriverId = "ricciardo",
                            FamilyName = "Ricciardo",
                            GivenName = "Daniel",
                            Nationality = "Australian",
                            PermanentNumber = 3
                        },
                        new
                        {
                            DriverId = "sainz",
                            FamilyName = "Sainz",
                            GivenName = "Carlos",
                            Nationality = "Spanish",
                            PermanentNumber = 55
                        },
                        new
                        {
                            DriverId = "leclerc",
                            FamilyName = "Leclerc",
                            GivenName = "Charles",
                            Nationality = "Monegasque",
                            PermanentNumber = 16
                        },
                        new
                        {
                            DriverId = "piastri",
                            FamilyName = "Piastri",
                            GivenName = "Oscar",
                            Nationality = "Australian",
                            PermanentNumber = 81
                        },
                        new
                        {
                            DriverId = "russell",
                            FamilyName = "Russell",
                            GivenName = "George",
                            Nationality = "British",
                            PermanentNumber = 63
                        },
                        new
                        {
                            DriverId = "alonso",
                            FamilyName = "Alonso",
                            GivenName = "Fernando",
                            Nationality = "Spanish",
                            PermanentNumber = 14
                        },
                        new
                        {
                            DriverId = "ocon",
                            FamilyName = "Ocon",
                            GivenName = "Esteban",
                            Nationality = "French",
                            PermanentNumber = 31
                        },
                        new
                        {
                            DriverId = "hulkenberg",
                            FamilyName = "Hulkenberg",
                            GivenName = "Nico",
                            Nationality = "German",
                            PermanentNumber = 27
                        },
                        new
                        {
                            DriverId = "stroll",
                            FamilyName = "Stroll",
                            GivenName = "Lance",
                            Nationality = "Canadian",
                            PermanentNumber = 18
                        },
                        new
                        {
                            DriverId = "tsunoda",
                            FamilyName = "Tsunoda",
                            GivenName = "Yuki",
                            Nationality = "Japanese",
                            PermanentNumber = 22
                        },
                        new
                        {
                            DriverId = "gasly",
                            FamilyName = "Gasly",
                            GivenName = "Pierre",
                            Nationality = "French",
                            PermanentNumber = 10
                        },
                        new
                        {
                            DriverId = "bearman",
                            FamilyName = "Bearman",
                            GivenName = "Oliver",
                            Nationality = "British",
                            PermanentNumber = 50
                        },
                        new
                        {
                            DriverId = "magnussen",
                            FamilyName = "Magnussen",
                            GivenName = "Kevin",
                            Nationality = "Danish",
                            PermanentNumber = 20
                        },
                        new
                        {
                            DriverId = "colapinto",
                            FamilyName = "Colapinto",
                            GivenName = "Franco",
                            Nationality = "Argentinian",
                            PermanentNumber = 43
                        },
                        new
                        {
                            DriverId = "schumacher",
                            FamilyName = "Schumacher",
                            GivenName = "Mick",
                            Nationality = "German",
                            PermanentNumber = 47
                        },
                        new
                        {
                            DriverId = "vettel",
                            FamilyName = "Vettel",
                            GivenName = "Sebastian",
                            Nationality = "German",
                            PermanentNumber = 5
                        },
                        new
                        {
                            DriverId = "latifi",
                            FamilyName = "Latifi",
                            GivenName = "Nicholas",
                            Nationality = "Canadian",
                            PermanentNumber = 6
                        },
                        new
                        {
                            DriverId = "Guanyu",
                            FamilyName = "Zhou",
                            GivenName = "Zhou",
                            Nationality = "Chinese",
                            PermanentNumber = 24
                        },
                        new
                        {
                            DriverId = "sargeant",
                            FamilyName = "Sargeant",
                            GivenName = "Logan",
                            Nationality = "American",
                            PermanentNumber = 2
                        },
                        new
                        {
                            DriverId = "albon",
                            FamilyName = "Albon",
                            GivenName = "Alexander",
                            Nationality = "Thai",
                            PermanentNumber = 23
                        },
                        new
                        {
                            DriverId = "deVries",
                            FamilyName = "de Vries",
                            GivenName = "Nyck",
                            Nationality = "Dutch",
                            PermanentNumber = 7
                        },
                        new
                        {
                            DriverId = "lawson",
                            FamilyName = "Lawson",
                            GivenName = "Liam",
                            Nationality = "New Zealander",
                            PermanentNumber = 36
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DriveToGetDataWebsitePrototype.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DriveToGetDataWebsitePrototype.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveToGetDataWebsitePrototype.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DriveToGetDataWebsitePrototype.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
